### PR TITLE
Added common libvirt constants, found by in libvirt c-api header files.

### PR DESCRIPTION
**Pull request by ksallberg**
There might be even more constants that I missed out due to the script I ran, but I think this covers many of them.

### CODE REVIEW

**Comment by msantos** [comment]
Thanks, this must have been a lot of work to put together! I'm happy to merge this without changes but a few questions:
* the public header files are libvirt.h and virterror.h. Do we need to pull in the internal constants?
* libvirt will add/remove constants over time and probably rename or change the value of constants. Any ideas on how we can keep this file up to date?

**Comment by ksallberg** [comment]
Right, we probably should not pull in internal constants.

What about creating a little script that runs through the header files, extracts constants and prints them out with the erlang hrl syntax? Might take some time to do this, but then we could run this whenever new versions of libvirt are released.

I guess another approach would be to include only a few constants that everyone will probably need, and then manually checking them whenever a new version is released, or create a script for this purpose too.

**Comment by msantos** [comment]
Either option works. While not 100% correct, maybe simply pulling out the enum's is enough?

Something like:
~~~
#!/usr/bin/awk -f                                                                                                                                                                                                   
                                                                                                                                                                                                                    
BEGIN { inenum = 0 }                                                                                                                                                                                                
                                                                                                                                                                                                                    
{                                                                                                                                                                                                                   
    if (/^typedef enum/) inenum = 1                                                                                                                                                                                 
    if (/^}/) inenum = 0                                                                                                                                                                                             
                                                                                                                                                                                                                    
    if (inenum) {                                                                                                                                                                                                   
        if ($1 ~ /^VIR_/) print $0                                                                                                                                                                                  
    }                                                                                                                                                                                                               
}
~~~

**Comment by ksallberg** [comment]
Ok something like that would be a good start. I will look into creating a script that does that, and then generates a .hrl file with -define(blabla, xx) for each enum value. this way we can run "diff scriptoutput oldhrl" to see if something changed in a new libvirt version, and if so use the newly generated hrl. How about that?

**Comment by msantos** [comment]
That would be perfect!

**Comment by ksallberg** [comment]
Allright, I created a script that takes text in the form of header files, and pulls out enum values following your script. Then transforms it into a hrl file. The updated libvirt_constants.hrl reflects the current state of libvirt master, although I couldnt find libvirt.h as you referred to but only libvirt_xyz.h files.

I dislike the awk...ward script file running many iterations on the output, is there a better way to do it?

**Comment by msantos** [comment]
That script actually works really well. I'm not sure if this is better but this does it all in awk rather than using pipes:
```
#!/usr/bin/awk -f

BEGIN { inenum = 0 } 

function ensure_comma(str) {
    if (str !~ /,/ && str ~ /\/\*/) {
        sub("\\/\\*", ", \\/\\*", str)
        return str
    }
    return str
}

function strip(str) {
    sub("^ *", "", str)
    sub(" *$", "", str)
    return str
}

function comment(str) {
    if (str) {
        return " % " str
    }
}

function term(str) {
    if (str ~ /^[0-9\-]+$/) {
        return str
    }
    else if (str ~ /^[A-Z0-9_]+$/) {
        return "?" str
    }
    else if (str ~ /<</) {
        sub("<<", "bsl", str)
        return str
    }
}

function define(name, val, comment) {
    return "-define(" strip(name) "," term(strip(val)) ")."
}

{
    if (/^typedef enum/) inenum = 1
    if (/^}/) inenum = 0

    if (inenum && $1 ~ /^VIR_/) {
        split(ensure_comma($0), a, "\=")
        split(a[2], b, ",")
        if (!length(b[1])) next
        print define(a[1], b[1], b[2])
    }
}
```
BTW, doesn't need to be an awk script if you'd rather use something else.

If it's not too much trouble, can you rebase your branch into 1 commit?

**Comment by ksallberg** [comment]
Hmm not sure if I did that the right way, never tried it before. If not, maybe you can reject this pull request and copy whatever you think is ok. I think your script is more clear

**Comment by msantos** [comment]
No prob, I was able to rebase your branch. I added the awk script as suggested on top of your patch but if you think of something better, please let me know.

Thank you for all of your work on this!

**Comment by ksallberg** [comment]
Very nice, we now have the problem that occasionally comments seem to not be removed, causing things like:

-define(VIR_ERR_ERROR,).

In my script I fixed it by removing all '/' right after attempting to remove comments.

**Pull request closed without merging**
